/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-06-13 18:14:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/admin/allcss.jsp", Long.valueOf(1618511708843L));
    _jspx_dependants.put("jar:file:/C:/java%20project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Banking-App/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/admin/main_navbar.jsp", Long.valueOf(1665811971359L));
    _jspx_dependants.put("jar:file:/C:/java%20project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Banking-App/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/admin/left-navbar.jsp", Long.valueOf(1662305828867L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1718216082224L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Bank:View Profile</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- fontawsome tag -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==\"\r\n");
      out.write("	crossorigin=\"anonymous\" />\r\n");
      out.write("\r\n");
      out.write("<link href=\"admin/style.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- js file -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"myjs.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f7e7e6;\">\r\n");
      out.write("	");
      out.write("<nav\r\n");
      out.write("	class=\"navbar navbar-expand-sm navbar-dark bg-primary flex-sm-nowrap flex-wrap\">\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<button class=\"navbar-toggler flex-grow-sm-1 flex-grow-0 me-2\"\r\n");
      out.write("			type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbar5\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<span class=\"navbar-brand flex-grow-1\">Banking System</span>\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"navbar-collapse collapse flex-grow-1 justify-content-center\"\r\n");
      out.write("			id=\"navbar5\">\r\n");
      out.write("			<ul class=\"navbar-nav mx-auto\">\r\n");
      out.write("				<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><i\r\n");
      out.write("						class=\"fas fa-file-invoice\"></i> Account</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\" href=\"#\"><i\r\n");
      out.write("						class=\"fas fa-address-card\"></i> Transaction</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"flex-grow-1\">\r\n");
      out.write("			<!--spacer-->\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("			<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><i\r\n");
      out.write("					class=\"fas fa-user-circle\"></i> Admin</a></li>\r\n");
      out.write("			<li class=\"nav-item\">\r\n");
      out.write("				<button class=\"btn btn-primary nav-link active\" data-toggle=\"modal\"\r\n");
      out.write("					data-target=\"#logoutMenu\">\r\n");
      out.write("					<i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("				</button>\r\n");
      out.write("			</li>\r\n");
      out.write("\r\n");
      out.write("		</ul>\r\n");
      out.write("\r\n");
      out.write("		<!-- Button trigger modal -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Modal -->\r\n");
      out.write("		<div class=\"modal fade\" id=\"logoutMenu\" tabindex=\"-1\" role=\"dialog\"\r\n");
      out.write("			aria-labelledby=\"exampleModalCenterTitle\" aria-hidden=\"true\">\r\n");
      out.write("			<div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("				<div class=\"modal-content\">\r\n");
      out.write("					<div class=\"modal-header bg-primary\">\r\n");
      out.write("						\r\n");
      out.write("						<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("							aria-label=\"Close\">\r\n");
      out.write("							<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-body\">\r\n");
      out.write("						<h5 class=\"text-center\">Do You Want Logout</h5>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"text-center\">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("							data-dismiss=\"modal\">Close</button>\r\n");
      out.write("						<a href=\"../logout\" type=\"button\" class=\"btn btn-primary\">Logout</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"modal-footer bg-primary\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>");
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container-fluid\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			");
      out.write("<!--    <div class=\"sidebar\">\r\n");
      out.write("  <a class=\"active\" href=\"#home\"><i class=\"fas fa-home\"></i> Home</a> \r\n");
      out.write("  <a href=\"#about\">About</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("  <h2>Responsive Sidebar Example</h2>\r\n");
      out.write("  <p>This example use media queries to transform the sidebar to a top navigation bar when the screen size is 700px or less.</p>\r\n");
      out.write("  <p>We have also added a media query for screens that are 400px or less, which will vertically stack and center the navigation links.</p>\r\n");
      out.write("  <h3>Resize the browser window to see the effect.</h3>\r\n");
      out.write("</div> -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"col-md-2 sidebar\">\r\n");
      out.write("\r\n");
      out.write("	<a class=\"active\" href=\"index.jsp\"><i class=\"fas fa-home\"></i> Home</a> \r\n");
      out.write("	\r\n");
      out.write(" 	<div class=\"dropdown\">\r\n");
      out.write("	<a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("		aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fas fa-user-circle\"></i> Account</a>\r\n");
      out.write("		<div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"open_acc.jsp\"><i class=\"fas fa-arrow-alt-circle-right\"></i> Open New Account</a>\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"all_user.jsp\"><i class=\"fas fa-arrow-alt-circle-right\"></i> All Account</a>\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"acc_status.jsp\"><i class=\"fas fa-arrow-alt-circle-right\"></i> Account Status</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"dropdown\">\r\n");
      out.write("	<a href=\"#about\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"\r\n");
      out.write("		aria-haspopup=\"true\" aria-expanded=\"false\"><i class=\"fas fa-address-card\"></i> Transaction</a>\r\n");
      out.write("		<div class=\"dropdown-menu\" aria-labelledby=\"menu2\">\r\n");
      out.write("			<a class=\"dropdown-item\" href=\"new_transaction.jsp\"><i class=\"fas fa-arrow-alt-circle-right\"></i> New Transaction</a>  \r\n");
      out.write("			<a class=\"dropdown-item\" href=\"all_trans.jsp\"><i class=\"fas fa-arrow-alt-circle-right\"></i> All Transaction</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div> \r\n");
      out.write("	\r\n");
      out.write("	<a class=\"active\" href=\"check_status.jsp\"><i class=\"fas fa-home\"></i> Cheque</a> \r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("			<div class=\"col-md-10 p-4 offset-md-2\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<!--  -->\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /admin/view_profile.jsp(16,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty userobj }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		");
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /admin/view_profile.jsp(17,2) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("../login.jsp");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /admin/view_profile.jsp(25,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<div class=\"card-body\">\r\n");
          out.write("							<div\r\n");
          out.write("								class=\"container d-flex justify-content-center align-items-center\">\r\n");
          out.write("								<div\r\n");
          out.write("									style=\"width: 100px; height: 100px; border: 1px black solid;\">\r\n");
          out.write("									<img alt=\"\" src=\"../img/pf.png\"\r\n");
          out.write("										style=\"width: 100px; height: 100px\">\r\n");
          out.write("								</div>\r\n");
          out.write("							</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("							<form action=\"\">\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">Account</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.accountNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("											readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">Balance</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">First\r\n");
          out.write("										Name</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.firstName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("											readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">Username</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">Email</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">Phone\r\n");
          out.write("										No</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">Date\r\n");
          out.write("										Of Birth</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.dob}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">Aadhar\r\n");
          out.write("										No</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.adhar}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">Address</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">City</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.city}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("								<div class=\"form-group row mt-3\">\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2 offset-sm-1 col-form-label col-form-label\">State</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("\r\n");
          out.write("									<label for=\"colFormLabel\"\r\n");
          out.write("										class=\"col-sm-2  col-form-label col-form-label\">Status</label>\r\n");
          out.write("									<div class=\"col-sm-3\">\r\n");
          out.write("										<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("											id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.status}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("									</div>\r\n");
          out.write("								</div>\r\n");
          out.write("\r\n");
          out.write("							</form>\r\n");
          out.write("						</div>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /admin/view_profile.jsp(50,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty bal }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("											<input type=\"email\" class=\"form-control form-control\"\r\n");
          out.write("												id=\"colFormLabel\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bal }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\">\r\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
